spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
logging:
  level:
    org.hibernate.SQL: debug